server:
  port: 8080
  servlet:
    context-path: /

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  ${db.url}
    username: ${db.username}
    password: ${db.password}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false

logging.level.org.springframework.data.elasticsearch.client.WIRE: trace

logging:
  file:
    path: ${log.path}
  config:
    classpath: logback-spring.xml